FROM dock.mau.dev/mautrix/telegram:v0.15.2

RUN yq -i '.bridge.filter.users |= null' example-config.yaml
RUN yq -i '.bridge.filter.users |= null' /data/config.yaml

CMD ['python3', '-m', 'mautrix_telegram', '-c', '/data/config.yaml']
